export const portfolioItems = [
  {
    id: "chatBot",
    title: "MacEwan University Chatbot",
    description: "Full Stack Web Application",
    skills: ["ReactJS", "Pinecone", "Cohere", "Langchain"],
    image: "chatbot.png",
    githubUrl: "https://github.com/fahad-ali1/MacEwan_Chatbot",
    liveUrl: "https://macewan-chatbot.onrender.com/",
    altText: "MacEwan University Chatbot interface screenshot",
  },
  {
    id: "youtubeAutomation",
    title: "YouTube Content Automation Pipeline",
    description: "AI-Powered Video Content Generation System",
    skills: [
      "Gemini",
      "ElevenLabs",
      "Edge TTS",
      "Whisper ASR",
      "Remotion",
      "Node.js",
    ],
    image: "automategpt-automation.png",
    altText: "YouTube Content Automation Pipeline interface screenshot",
  },
  {
    id: "coupOnlineGame",
    title: "Coup Card Game (Online Remake)",
    description: "Full Stack Web Game",
    skills: ["Vite", "Node.js", "MongoDB", "ShadCN", "Tailwind CSS", "Git"],
    image: "coup-online-game.png",
    githubUrl: "https://github.com/batec2/CoupOnline",
    altText: "Coup Online Game interface screenshot",
  },
  {
    id: "courseRegisterWebApp",
    title: "Class Scheduler Web Application",
    description: "Full Stack Web Application",
    skills: ["ReactJS", "Node.js", "MongoDB", "Git"],
    image: "class-scheduler-webapp.png",
    githubUrl: "https://github.com/fahad-ali1/course_registration_system",
    liveUrl: "https://course-register.onrender.com/",
    altText: "Class Scheduler Web Application interface screenshot",
  },
  {
    id: "personalServerProject",
    title: "Personal Server Project",
    description: "Self-hosted Services",
    skills: ["Linux", "Networking", "Docker", "SSH", "Scripting"],
    image: "raspberrypi5-stock-image.jpg",
    altText: "Raspberry Pi 5 server setup",
  },
  {
    id: "website2",
    title: "Personal Portfolio Website (V2)",
    description: "Updated Portfolio Website",
    skills: ["ReactJS", "Git"],
    image: "personal-website2-demo.png",
    githubUrl: "https://github.com/fahad-ali1/fahad-ali",
    altText: "Personal Portfolio Website V2 screenshot",
  },
  {
    id: "website1",
    title: "Personal Portfolio Website (V1)",
    description: "Original Portfolio Website to learn ReactJS",
    skills: ["ReactJS", "Git"],
    image: "personal-website-demo.png",
    githubUrl: "https://github.com/fahad-ali1/fahad-ali/tree/backupV1",
    altText: "Personal Portfolio Website V1 screenshot",
  },
  {
    id: "game",
    title: "2D Space Shooter Game",
    description: "Game made with Python",
    skills: ["Python", "Python Arcade", "Git"],
    image: "space-blaster-demo.png",
    githubUrl: "https://github.com/fahad-ali1/Space-Blaster",
    altText: "Space Blaster game screenshot",
  },
  {
    id: "propertyAssessments",
    title: "Property Assessments Application",
    description: "An app to Create Assessments of Properties in Edmonton",
    skills: ["Java", "SQL", "Git"],
    image: "property-assessment-app.png",
    githubUrl: "https://github.com/fahad-ali1/PropertyAssessmentGUI",
    altText: "Property Assessments Application interface",
  },
  {
    id: "scheduler",
    title: "Class Scheduling App",
    description: "An app Created Using Python and PyQT 5",
    skills: ["Python", "PyQt5", "Git"],
    image: "class-scheduler-demo.png",
    githubUrl: "https://github.com/fahad-ali1/CMPT-395-Class-Scheduler",
    altText: "Class Scheduling App interface",
  },
];
